variables:
  - group: Terraform_Backend
  - group: FleetManagement_Infrastructure

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Bash@3
    displayName: "Debug: System Information"
    inputs:
      targetType: "inline"
      script: |
        echo "Check pre-installed Terraform version:"
        terraform --version
        which terraform
        echo "----------------------------------------------------"
        echo "Backend Variables:"
        echo "  asa_name: $(asa_name)"
        echo "  asa_bs_name: $(asa_bs_name)"
        echo "  resource_group_name: $(resource_group_name)"
        echo "  azurerm_service_connection: $(azurerm_service_connection)"
        echo "Fleet Management Variables:"
        echo "  fm_resource_group_name: $(fm_resource_group_name)"
        echo "  fm_location: $(fm_location)"

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: "latest"

  - task: Bash@3
    displayName: "Verify Terraform Installation"
    inputs:
      targetType: "inline"
      script: |
        echo "Check installed terraform version: $(terraform -version)"

  - task: Bash@3
    displayName: "Debug: List Infrastructure folder"
    inputs:
      targetType: "inline"
      script: |
        echo "=== Actual working directory (PWD) ==="
        pwd

        echo "=== Content of main directory ==="
        ls -la $(System.DefaultWorkingDirectory)

  - task: TerraformTaskV4@4
    displayName: "Terraform Init"
    inputs:
      provider: "azurerm"
      command: "init"
      backendServiceArm: "$(azurerm_service_connection)"
      backendAzureRmResourceGroupName: "$(resource_group_name)"
      backendAzureRmStorageAccountName: "$(asa_name)"
      backendAzureRmContainerName: "$(asa_bs_name)"
      backendAzureRmKey: "fleetmanagement-infrastructure.tfstate"

  - task: TerraformTaskV4@4
    displayName: "Terraform Plan"
    inputs:
      provider: "azurerm"
      command: "plan"
      environmentServiceNameAzureRM: "$(azurerm_service_connection)"
      commandOptions: '-var="shared_resource_group_name=$(fm_resource_group_name)" -var="location=$(fm_location)"'

  - task: TerraformTaskV4@4
    displayName: "Terraform Apply"
    inputs:
      provider: "azurerm"
      command: "apply"
      environmentServiceNameAzureRM: "$(azurerm_service_connection)"
      commandOptions: '-var="shared_resource_group_name=$(fm_resource_group_name)" -var="location=$(fm_location)"'
